# A

In [5]:
s = input()
count = 0
for i in range(len(s)-1):
    if s[i:i+2] == "AC":
        count = 1
        break
if count == 1:
    print("Yes")
else:
    print("No")

ACACA
Yes


# B

In [22]:
n = int(input())
a_list = input().split()
a_list = [int(x) for x in a_list]

zentori = 3**n

a_list_2 = [x%2 for x in a_list]
from collections import Counter

counter = Counter(a_list_2)

bad_tori = (2**counter[0])

print(zentori-bad_tori)

10
90 52 56 71 44 8 13 30 57 84
58921


In [12]:
a_list

[2, 3]

In [18]:
a_list_2



1

In [9]:
243*243

59049

In [10]:
2*2*2*1*2*2*1*2*1*2

128

In [11]:
59049-128

58921

# C

In [95]:
import numpy as np
s = input()
s_list = [i for i in s]
s_without_x = [i for i in s_list if i != "x"]

oxxx


In [108]:
a = np.array(list("abc"))

In [118]:
import numpy as np
s = input()
s_list = list(s)
s_array = np.array(s_list)
s_without_x_ar = s_array[s_array != "x"]

abb


In [120]:
len(s_without_x_ar)

3

In [188]:
import numpy as np
s = input()
s_list = list(s)
s_array = np.array(s_list)
s_without_x_ar = s_array[s_array != "x"]

if (s_without_x_ar != s_without_x_ar[::-1]).any():
    print(-1)
else:
    kw_count = len(s_without_x_ar)
    if kw_count == 0:
        print(0)
    elif kw_count % 2 == 0:
        half_s_wox_left = s_without_x_ar[:int(kw_count/2)]
        lastw_count = len(half_s_wox_left[half_s_wox_left==half_s_wox_left[-1]])
        check_last_idx = np.where(s_array == half_s_wox_left[-1])[0][lastw_count-1]
        half_array = s_array[:check_last_idx+1]
        
        
        a = np.where(half_array!="x")[0]
        a = np.insert(a,0,-1)
        left_count_ar = a[1:] - a[:-1] - 1


        # right
        half_s_wox_right = s_without_x_ar[int(kw_count/2):]
        half_s_wox_right_back = half_s_wox_right[::-1]
        s_array_back = s_array[::-1]

        lastw_count = len(half_s_wox_right_back[half_s_wox_right_back==half_s_wox_right_back[-1]])
        check_last_idx = np.where(s_array_back == half_s_wox_right_back[-1])[0][lastw_count-1]

        half_array = s_array_back[:check_last_idx+1]
        
        a = np.where(half_array!="x")[0]
        a = np.insert(a,0,-1)
        right_count_ar = a[1:] - a[:-1] - 1
        
        print(np.abs(right_count_ar - left_count_ar).sum())
        
    else:
        half_s_wox_left = s_without_x_ar[:int(kw_count//2+1)]
        lastw_count = len(half_s_wox_left[half_s_wox_left==half_s_wox_left[-1]])
        check_last_idx = np.where(s_array == half_s_wox_left[-1])[0][lastw_count-1]
        half_array = s_array[:check_last_idx+1]
        
        
        a = np.where(half_array!="x")[0]
        a = np.insert(a,0,-1)
        left_count_ar = a[1:] - a[:-1] - 1


        # right
        half_s_wox_right = s_without_x_ar[int(kw_count//2):]
        half_s_wox_right_back = half_s_wox_right[::-1]
        s_array_back = s_array[::-1]

        lastw_count = len(half_s_wox_right_back[half_s_wox_right_back==half_s_wox_right_back[-1]])
        check_last_idx = np.where(s_array_back == half_s_wox_right_back[-1])[0][lastw_count-1]

        half_array = s_array_back[:check_last_idx+1]
        
        a = np.where(half_array!="x")[0]
        a = np.insert(a,0,-1)
        right_count_ar = a[1:] - a[:-1] - 1
        
        print(np.abs(right_count_ar - left_count_ar).sum())
            
        
#         s_ar = np.array(s_list)
        
        
        
#         for i in range(len(half_s_wox_left)):
#             count = np.min(np.where(s_ar == half_s_wox_left[i]))
#             left_count_list.append(count)
#             s_ar = s_ar[count+1:]
            
#         half_s_wox_right = s_without_x[int(kw_count/2):]
#         s_ar_back = np.array(s_list[::-1])
#         half_s_wox_right_back = half_s_wox_right[::-1]
#         for i in range(len(half_s_wox_right_back)):
#             count = np.min(np.where(s_ar_back == half_s_wox_right_back[i]))
#             right_count_list.append(count)
#             s_ar_back = s_ar_back[count+1:]
            
#         sousa_count = 0
#         for i in range(len(left_count_list)):
#             sousa_count += np.abs(left_count_list[i] - right_count_list[i])
        
#         print(sousa_count)
#     else:
#         half_s_wox_left = s_without_x[:int(kw_count//2+1)]
#         s_ar = np.array(s_list)
#         for i in range(len(half_s_wox_left)):
#             count = np.min(np.where(s_ar == half_s_wox_left[i]))
#             left_count_list.append(count)
#             s_ar = s_ar[count+1:]
            
#         half_s_wox_right = s_without_x[int(kw_count//2):]
#         s_ar_back = np.array(s_list[::-1])
#         half_s_wox_right_back = half_s_wox_right[::-1]
#         for i in range(len(half_s_wox_right_back)):
#             count = np.min(np.where(s_ar_back == half_s_wox_right_back[i]))
#             right_count_list.append(count)
#             s_ar_back = s_ar_back[count+1:]
            
#         sousa_count = 0
#         for i in range(len(left_count_list)):
#             sousa_count += np.abs(left_count_list[i] - right_count_list[i])
        
#         print(sousa_count)

sx
1


In [164]:
left_count_ar - right_count_ar

array([1, 0, 0])

In [167]:
np.abs(right_count_ar - left_count_ar).sum()

1

In [155]:
a = np.where(half_array!="x")[0]
a = np.insert(a,0,-1)
b = a[1:] - a[:-1] - 1

In [156]:
a

array([4, 5, 6])

In [158]:
a

array([-1,  4,  5,  6])

In [160]:
b

array([4, 0, 0])

In [141]:
np.where(half_array=="x")

(array([0, 1, 2, 3]),)

In [129]:
np.where(s_array == half_s_wox_left[-1])#[0][lastw_count]

(array([2, 3, 4, 5]),)

In [78]:
right_count_list

[0, 0]

In [57]:
left_count_list

[]

In [45]:
import numpy as np
s_ar = np.array(s_list)

In [53]:
np.min(np.where(s_ar == "a"))

0

In [50]:
s_ar

array(['a', 's', 'a'], 
      dtype='<U1')

In [44]:
s_list"a"

False

In [33]:
s

['s', 'd']

# D

In [191]:
import numpy as np
from collections import Counter
s = np.array(list(input()))



abcabcxabcx


In [194]:
unique_s = np.unique(s)

In [197]:
eye = np.eye(len(unique_s))

In [202]:
unique_s

ValueError: shape mismatch: objects cannot be broadcast to a single shape