In [1]:
S = input()

print(S[:-8])

YAKINIKUFESTIVAL
YAKINIKU


# B

In [18]:
n = int(input())
d_list = input().split()
d_list = [int(x) for x in d_list]

m = int(input())
t_list = input().split()
t_list = [int(x) for x in t_list]

from collections import Counter

count_d = Counter(d_list)
count_t = Counter(t_list)

check = 0
for key, value in count_t.items():
    if count_d[key] < value:
        check = 1
        break

if check == 0:
    print("YES")
else:
    print("NO")
    

15
1 2 2 3 3 3 4 4 4 4 5 5 5 5 5
9
5 4 3 2 1 2 3 4 5
YES


In [ ]:
7
100 200 500 700 1200 1600 2000
6
100 200 500 700 1600 1600

In [ ]:
1
800
5
100 100 100 100 100

In [ ]:
15
1 2 2 3 3 3 4 4 4 4 5 5 5 5 5
9
5 4 3 2 1 2 3 4 5

In [4]:
from collections import Counter

count_d = Counter(d_list)
count_t = Counter(t_list)

In [15]:
check = 0
for key, value in count_t.items():
    if count_d[key] < value:
        check = 1
        break

if check == 0:
    print("YES")
else:
    print("NO")
    

YES


In [14]:
count_d[1]

2

# C

In [22]:
N, M = map(int, input().split())
ab_list = []
for _ in range(m):
    a, b = map(int, input().split())
    ab_list.append([a,b])

6 5
1 2
2 3
3 4
4 5
5 6


In [20]:
6 5
1 2
2 3
3 4
4 5
5 6

[[1, 1]]

# D

In [97]:
n = int(input())
s = input()

50
10101000010011011110001001111110000101010111100110


In [98]:
s = [int(x) for x in s]
l = len(s)
import numpy as np
ar_1 = np.array(s[:-2]).reshape([l-2,1])
ar_2 = np.array(s[1:-1]).reshape([l-2,1])
ar_3 = np.array(s[2:]).reshape([l-2,1])
ar = np.hstack((ar_1,ar_2,ar_3))
check_ar = (ar == [1,0,1]).all(axis=1)
check_index = np.where(check_ar==True)[0]

In [99]:
check_index 

array([ 0,  2, 13, 35, 37, 39])

In [94]:
s = [int(x) for x in s]
l = len(s)
import numpy as np



count = 0
while 1>0:
    ar_1 = np.array(s[:-2]).reshape([l-2,1])
    ar_2 = np.array(s[1:-1]).reshape([l-2,1])
    ar_3 = np.array(s[2:]).reshape([l-2,1])
    ar = np.hstack((ar_1,ar_2,ar_3))
    check_ar = (ar == [1,0,1]).all(axis=1)
    check_index = np.where(check_ar==True)[0]
    if len(check_index)>0:
        if min(check_index) <= l - max(check_index) - 1:
            s[min(check_index):min(check_index)+3] = [0,1,0]
            print(min(check_index))
        else:
            s[max(check_index):max(check_index)+3] = [0,1,0]
            print(max(check_index))
        count += 1
#         print()
    else:
        break

print(count)


0
39
40
41
42
13
12
35
8


In [88]:
10101000010011011110001001111110000101010111100110

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)

In [ ]:
# for i in range(l-2):
#     if s[i:i+3] == [1,0,1]:
#         check_list.append(1)
#     else:
#         check_list.append(0)


In [64]:
ar_1 = np.array(s[:-2]).reshape([l-2,1])
ar_2 = np.array(s[1:-1]).reshape([l-2,1])
ar_3 = np.array(s[2:]).reshape([l-2,1])
ar = np.hstack((ar_1,ar_2,ar_3))
check_ar = (ar == [1,0,1]).all(axis=1)
check_index = np.where(check_ar==True)
if len(check_index)>0:
    if min(check_index) <= l - max(check_index) - 1:
        ar[min(check_index)] = [0,1,0]
    else:
        ar[max(check_index)] = [0,1,0]
    count += 1
else:
    break

print(count)


In [66]:
ar = np.hstack((ar_1,ar_2,ar_3))
check_ar = (ar == [1,0,1]).all(axis=1)
check_index = np.where(check_ar==True)
if len(check_index)>0:
    if min(check_index) <= l - max(check_index) - 1:
        ar[min(check_index)] = [0,1,0]
    else:
        ar[max(check_index)] = [0,1,0]
    count += 1
else:
    break

print(count)


In [72]:
ar == [1,0,1]

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False],
       [False,  True,  True],
       [False, False,  True],
       [ True, False, False],
       [ True,  True,  True],
       [False, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False, False],
       [ True,  True, False],
       [False,  True, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False],
       [False,  True,  True],
       [False, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False, False],
       [ True,  True, False],
       [False,  True, False],
       [False,  True, False],
       [Fa

In [75]:
check_ar = (ar == [1,0,1]).all(axis=1)
check_index = np.where(check_ar==True)
if len(check_index)>0:
    if min(check_index) <= l - max(check_index) - 1:
        ar[min(check_index)] = [0,1,0]
    else:
        ar[max(check_index)] = [0,1,0]
    count += 1
else:
    break

print(count)


In [77]:
check_ar

array([ True, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False], dtype=bool)

In [78]:
check_index = np.where(check_ar==True)
if len(check_index)>0:
    if min(check_index) <= l - max(check_index) - 1:
        ar[min(check_index)] = [0,1,0]
    else:
        ar[max(check_index)] = [0,1,0]
    count += 1
else:
    break

print(count)


In [79]:
if len(check_index)>0:
    if min(check_index) <= l - max(check_index) - 1:
        ar[min(check_index)] = [0,1,0]
    else:
        ar[max(check_index)] = [0,1,0]
    count += 1
else:
    break

print(count)


SyntaxError: 'break' outside loop (<ipython-input-79-a73e16c61525>, line 8)

In [48]:
np.array([s[:-2],s[1:-1],s[2:]]).reshape()

array([[1, 0, 1],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [0, 0, 0],
       [1, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 0, 1],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 0, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 1, 0]])

In [39]:
len(check_list)

48

In [27]:
i = 0
while i>=0:
    i += 1
    print(i)
    if i>10:
        break

1
2
3
4
5
6
7
8
9
10
11


# 反省
* A,Bしか終えられなかった。
* Cはグラフの問題で、少し考えたがわからなそうだったので、スルーしてDに挑む。
* しかしDも解けず。はじめに、「両側から徐々に101の組みを探すだけでいいのでは」と見積もり、numpyに若干苦戦しながら進め、時間を無駄にした。(上記のコードは無駄コード)
* その後、101と隣接する1が重要である、ということはわかったが、どのようにロジックを組めばいいかわからず、終了。
* 解説を見ても、よくわからない。改めてみる。