# A

# B

In [4]:
import numpy as np
n = int(input())
a_list = [int(x) for x in input().split()]

7
0 0 1 0 0 2 4


In [11]:
narabi = np.arange(n)
either_kiri = []
for i,a in enumerate(a_list):
    if a > 0:
        for j in range(a):
            either_kiri.append((i,narabi[i-j-1]))
        narabi= np.hstack((narabi[:i-a],narabi[i],narabi[i-a:i],narabi[i+1:]))
    print(narabi)
    print(either_kiri)

[0 1 2 3 4 5 6]
[]
[0 1 2 3 4 5 6]
[]
[0 2 1 3 4 5 6]
[(2, 1)]
[0 2 1 3 4 5 6]
[(2, 1)]
[0 2 1 3 4 5 6]
[(2, 1)]
[0 2 1 5 3 4 6]
[(2, 1), (5, 4), (5, 3)]
[0 2 6 1 5 3 4]
[(2, 1), (5, 4), (5, 3), (6, 4), (6, 3), (6, 5), (6, 1)]


In [14]:
from collections import Counter
Counter(either_kiri)

Counter({(2, 1): 1,
         (5, 3): 1,
         (5, 4): 1,
         (6, 1): 1,
         (6, 3): 1,
         (6, 4): 1,
         (6, 5): 1})