# A

In [ ]:
import numpy as np

n = int(input())
a_list = input().split()
a_list = [int(a) for a in a_list]

b_list = input().split()
b_list = [int(b) for b in b_list]

c_list = input().split()
c_list = [int(c) for c in c_list]
# a_ar = np.unique(np.array(a_list))
# b_ar = np.unique(np.array(b_list))
# c_ar = np.unique(np.array(c_list))
a_ar = np.array(a_list)
b_ar = np.array(b_list)
c_ar = np.array(c_list)
count = 0
for a in a_ar:
    for b in b_ar[b_ar>a]:
        count += len(c_ar[c_ar>b])

print(count)

In [1]:
import numpy as np

In [67]:
import numpy as np

n = int(input())
a_list = input().split()
a_list = [int(a) for a in a_list]

b_list = input().split()
b_list = [int(b) for b in b_list]

c_list = input().split()
c_list = [int(c) for c in c_list]

a_ar = np.sort(np.array(a_list))
b_ar = np.sort(np.array(b_list))
c_ar = np.sort(np.array(c_list))

goukei = 0
for b in b_ar:
    goukei += len(a_ar[a_ar<b]) * len(c_ar[c_ar>b])
    
print(goukei)

3
3 2 1
4 5 6
7 9 8


array([7, 8, 9])

In [66]:
np.sort(b_ar)

array([4, 5, 6])

In [12]:
b_count_ar = np.sum(b_ar[:,np.newaxis]<c_ar,axis=1)

In [13]:
b_count_ar

array([2, 1, 0])

In [18]:
a_count = (a_ar[:,np.newaxis]<b_ar).astype(int)

In [19]:
a_count

array([[0, 1, 1],
       [0, 0, 1],
       [0, 0, 0]])

In [21]:
a_count * b_count_ar

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
np.sum([[0,0,0],[0,0,0]])

0

In [ ]:

# print(b_count_ar)
a_count = (a_ar[:,np.newaxis]<b_ar).astype(int)
# print(a_count)

print(np.sum(a_count * b_count_ar))

### a_ar = np.arange(10000)
b_ar = np.arange(10000,20000)
c_ar = np.arange(20000,30000)

In [3]:
b_count_ar = np.sum(b_ar[:,np.newaxis]<c_ar,axis=1)
# print(b_count_ar)
a_count = (a_ar[:,np.newaxis]<b_ar).astype(int)
# print(a_count)

print(np.sum(a_count * b_count_ar))

1000000000000


In [4]:
10000**3

1000000000000

In [ ]:
np.sum(a_count * b_count_ar)

In [31]:
hoge = np.arange(6).reshape([2,3])

In [32]:
fuga = hoge

In [35]:
hoge*fuga

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [34]:
np.sum(hoge*fuga)

55

In [ ]:


print(np.sum((a_ar[:,np.newaxis]<b_ar).astype(int) * b_count_ar))

6
3 14 159 2 6 53
58 9 79 323 84 6
2643 383 2 79 50 288

In [ ]:
b_ar[:,np.newaxis]>a_ar

In [ ]:
b_

In [ ]:
b_count_ar

In [ ]:
b_count_ar = np.sum(c_ar[:,np.newaxis]>b_ar,axis=1)

In [ ]:
b_count_ar

In [ ]:
np.sum((b_ar[:,np.newaxis]>a_ar).astype(int) * b_count_ar)

In [ ]:
b_count_ar = np.sum(b_ar[:,np.newaxis]>c_ar,axis=1)


In [ ]:
b_count_ar

In [ ]:
b_count

In [ ]:
c_ar

In [ ]:
6
3 14 159 2 6 53
58 9 79 323 84 6
2643 383 2 79 50 288

In [ ]:
count

In [ ]:
np.unique(np.array([1,1,1]))

In [46]:
#　https://beta.atcoder.jp/contests/arc084/submissions/1738773
from bisect import bisect_left
N = int(input())
A = sorted(int(x) for x in input().split())
B = sorted(int(x) for x in input().split())
C = sorted(int(x) for x in input().split())
cnt = [0] * (N + 1)

3
1 2 3
4 5 6
7 8 9


In [47]:
cnt

[0, 0, 0, 0]

In [49]:

for i, b in enumerate(B):
    print(cnt)
    cnt[i + 1] = bisect_left(A, b)
    print(cnt[i+1])
    cnt[i + 1] += cnt[i]
    print(cnt[i+1])

print(sum(cnt[bisect_left(B, c)] for c in C))

[0, 0, 0, 0]
3
3
[0, 3, 0, 0]
3
6
[0, 3, 6, 0]
3
9
27


In [51]:
A

[1, 2, 3]

In [56]:
bisect_left(A, 5)

3

# B

In [ ]:
k = int(input())

min_sum = 100

for i in range(1,10):
    k_ = k*i
#     print(k_)
    str_list = list(str(k_))
    num_list = [int(x) for x in str_list]
    if min_sum > sum(num_list):
        min_sum = sum(num_list)    

print(min_sum)

In [ ]:
list(str(6666))

In [ ]:
sum([1,1,1,])