# A

In [4]:
n = input()
a = input()
n = int(n)
a = int(a)

print(n**2-a)

10
0
100


# B

In [8]:
n = int(input())
k = int(input())
x_list = input().split()
x_list = [int(x) for x in x_list]

goukei = 0
for x in x_list:
    if abs(0-x) > abs(k-x):
        goukei += 2*abs(k-x)
    else:
        goukei += 2*abs(x)

print(goukei)

5
20
11 12 9 17 12
74


# C

In [37]:
x_list = input().split()
a = 100*int(x_list[0])
b = 100*int(x_list[1])
c = int(x_list[2])
d = int(x_list[3])
e = int(x_list[4])
f = int(x_list[5])

max_sato = e*f/100//1
max_mizu = f

def all_pattern(a,b,c):
    max_a = int(c//a)
    all_list = []
    for i in range(max_a+1):
        goukei = 0
        goukei += a*i
        j = 0
        while goukei <= c:
            if not goukei in all_list:
                all_list.append(goukei)
            goukei += b
    return all_list

mizu_pattern = all_pattern(a,b,max_mizu)
sato_pattern = all_pattern(c,d,max_sato)

satosui_situryo = 0
sato_situryo = 0
max_noudo = 0

for mizu in mizu_pattern:
    for sato in sato_pattern:
#         print(sato,mizu)
        if sato + mizu > 0:
            tmp_noudo = sato/(sato+mizu)*100
#             print(tmp_noudo)
            if max_noudo < tmp_noudo and tmp_noudo <= e/(100+e)*100 and mizu+sato <= f:
                max_noudo = tmp_noudo
                satosui_situryo = mizu + sato
                sato_situryo = sato
#                 print("a:",max_noudo,satosui_situryo,sato_situryo)

if satosui_situryo == 0:
    satosui_situryo += a

print(satosui_situryo,sato_situryo)
        
            
        

1 2 1000 10000 10 100
100 0


In [11]:
def all_pattern(a,b,c):
    max_a = c//a
    all_list = []
    for i in range(max_a+1):
        goukei = 0
        goukei += a*i
        j = 0
        while goukei <= c:
            if not goukei in all_list:
                all_list.append(goukei)
            goukei += b
    return all_list

In [12]:
all_pattern(2,3,10)

[0, 3, 6, 9, 2, 5, 8, 4, 7, 10]

In [14]:
3.6//1

3.0

# D

In [60]:
import numpy as np

n = int(input())
a_all = []
for i in range(n):
    a_list = input().split()
    a_list = [int(a) for a in a_list]
    a_all.append(a_list)

a_array = np.array(a_all)
# for i in range(n):
#     a_array[i][:i] = 0

a_goukeiyou = np.copy(a_array)
    
huseiritsu = 0
for i in range(n-2):
    for j in range(i+1,n-1):
        for k in range(j+1,n):
            hen1 = a_array[i][j]
            hen2 = a_array[j][k]
            hen3 = a_array[i][k]
            if hen1 <= hen2 + hen3 and hen2 <= hen1+hen3 and hen3 <= hen1 + hen2:
                if hen1 == hen2 + hen3:
                    a_goukeiyou[i][j]=0
                    a_goukeiyou[j][i]=0
                elif hen2 == hen3 + hen1:
                    a_goukeiyou[j][k]=0
                    a_goukeiyou[k][j]=0
                elif hen3 == hen1 + hen2:
                    a_goukeiyou[i][k]=0
                    a_goukeiyou[k][i]=0
            else:
                huseiritsu = 1
                break
        if huseiritsu ==1:
            break
    if huseiritsu == 1:
        break

if huseiritsu == 1:
    print("-1")
else:
    print(a_goukeiyou.sum()/2)
                
                    

3
0 1000000000 1000000000
1000000000 0 1000000000
1000000000 1000000000 0
3000000000


In [56]:
3
0 1000000000 1000000000
1000000000 0 1000000000
1000000000 1000000000 0

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [57]:
a_array

array([[0, 1, 3],
       [0, 0, 2],
       [0, 0, 0]])

In [53]:
for i in range(1):
    print(i)

0


In [48]:
a_array

array([[0, 1, 3],
       [0, 0, 2],
       [0, 0, 0]])

In [40]:
range(2,4)

range(2, 4)

In [61]:
for i in range(10):
    for j in range(10):
        print(i,j)
        if j == 5:
            break

0 0
0 1
0 2
0 3
0 4
0 5
1 0
1 1
1 2
1 3
1 4
1 5
2 0
2 1
2 2
2 3
2 4
2 5
3 0
3 1
3 2
3 3
3 4
3 5
4 0
4 1
4 2
4 3
4 4
4 5
5 0
5 1
5 2
5 3
5 4
5 5
6 0
6 1
6 2
6 3
6 4
6 5
7 0
7 1
7 2
7 3
7 4
7 5
8 0
8 1
8 2
8 3
8 4
8 5
9 0
9 1
9 2
9 3
9 4
9 5


In [63]:
a_array[1][2]

1000000000