# A

# B

In [30]:
import numpy as np
from collections import Counter

n = int(input())
a_list = [int(x) for x in input().split()]

narabi = np.arange(n)
either_kiri = []
for i,a in enumerate(a_list):
    if a > 0:
        for j in range(a):
            either_kiri.append([i,narabi[i-j-1]])
        narabi= np.hstack((narabi[:i-a],narabi[i],narabi[i-a:i],narabi[i+1:]))
#     print(narabi)
#     print(either_kiri)

ek_array = np.array(either_kiri)
count = 0
while len(ek_array)>0:
    c = Counter(ek_array.flatten())
    most_common_i = c.most_common()[0][0]
    ek_array = np.delete(ek_array, np.where(ek_array==most_common_i)[0],0)
    count += 1
print(n-count)

4
0 1 2 3
[0 1 2 3]
[]
[1 0 2 3]
[[1, 0]]
[2 1 0 3]
[[1, 0], [2, 0], [2, 1]]
[3 2 1 0]
[[1, 0], [2, 0], [2, 1], [3, 0], [3, 1], [3, 2]]
1


# 反省
* 上記で提出したが、TLE。
* 下記はそれを改善しようとしてるものだが、まだ途中。
* どうすれば時間短縮できるんだろうか。whileとforをどうにかするのだとは思う。
* 解説がないのが辛い。

# B_2

In [31]:
import numpy as np
from collections import Counter

n = int(input())
a_list = [int(x) for x in input().split()]

narabi = np.arange(n)
either_kiri_count = np.zeros(n)
for i,a in enumerate(a_list):
    if a > 0:
#         for j in range(a):
#             either_kiri.append([i,narabi[i-j-1]])
        either_kiri_count[i] += a
        either_kiri_count[i-a:i] += 1
        narabi= np.hstack((narabi[:i-a],narabi[i],narabi[i-a:i],narabi[i+1:]))
#     print(narabi)
#     print(either_kiri)

ek_array = np.array(either_kiri)
count = 0
while len(ek_array)>0:
    most_common_i = np.where(either_kiri_count==either_kiri_count.max())[0]
    ek_array = np.delete(ek_array, np.where(ek_array==most_common_i)[0],0)
    count += 1
print(n-count)

7
0 0 1 0 0 2 4


KeyboardInterrupt: 

In [29]:
from collections import Counter
count = 0
while len(ek_array)>0:
    c = Counter(ek_array.flatten())
    most_common_i = c.most_common()[0][0]
    ek_array = np.delete(ek_array, np.where(ek_array==most_common_i)[0],0)
    count += 1
print(n-count)

4


In [27]:
ek_array

array([], shape=(0, 2), dtype=int64)

In [21]:
ek_array = np.delete(ek_array, np.where(ek_array==6)[0],0)

array([[2, 1],
       [5, 4],
       [5, 3]])

In [22]:
ek_array

array([[2, 1],
       [5, 4],
       [5, 3],
       [6, 4],
       [6, 3],
       [6, 5],
       [6, 1]])