In [79]:
a,b,c = input().split()
a = int(a)
b = int(b)
c = int(c)

if a <= c and c <= b:
    print("Yes")
else:
    print("No")

-100 100 50
Yes


In [74]:
-100 <= 50

True

In [75]:
50 <= 100

True

In [76]:
True and True

True

In [77]:
-100 <= 50 <= 100

True

# B Counting Roads

In [20]:
import numpy as np
n,m = input().split()
n = int(n)
m = int(m)
count = np.zeros(n)
for i in range(m):
    a, b = input().split()
    count[int(a)-1] += 1
    count[int(b)-1] += 1

for i in count:
    print(int(i))

8 8
1 2
3 4
1 5
2 8
3 7
5 2
4 1
6 8
3
3
2
2
2
1
1
2


## import numpy as np
c = np.zeros(10)
for i in c:
    print(int(i))

# C bigarray

In [84]:
import numpy as np
n,k = input().split()
n = int(n)
k = int(k)
l = list()
for i in range(n):
    a, b = input().split()
    l.append([int(a),int(b)])

ar = np.array(l)
ar_s = ar.sort(0)
count = np.cumsum(ar_s[:,1])

print(ar_s)
print(count)
print(int(ar_s[np.where(count >=k)[0][0]][0]))

3 4
-1 1
-2 2
-3 3


TypeError: 'NoneType' object is not subscriptable

In [91]:
l = list([[1,2],[2,3],[1,4]])

In [92]:
a = np.array(l)

In [93]:
a

array([[1, 2],
       [2, 3],
       [1, 4]])

In [95]:
a[a[:,0].argsort()]

array([[1, 2],
       [1, 4],
       [2, 3]])

In [87]:
b = np.sort(a,axis=0)

In [89]:
a.sort(0)

In [90]:
a

array([[1, 2],
       [1, 3],
       [2, 4]])

In [88]:
b

array([[1, 2],
       [1, 3],
       [2, 4]])

In [54]:
c = np.cumsum(b[:,1])

In [56]:
np.where(c >=5)[0][0]

1

In [58]:
print(b[np.where(c >=5)[0][0]][0])

1


In [21]:
a = list()
a.append(int(2) * 3)

In [22]:
a

[6]

# D Score Attack

In [69]:
n,m = input().split()
n = int(n)
m = int(m)
l = list()
for i in range(m):
    a,b,c = input().split()
    l.append([int(a),int(b),int(c)])
    
print(l)

2 2
1 2 1
2 1 1
[[1, 2, 1], [2, 1, 1]]


In [ ]:
for i in range(m):
    while 
    

In [71]:
np.array([[1,2],[1,2,3]])

array([[1, 2], [1, 2, 3]], dtype=object)

# C

In [1]:
from ipywidgets import Textarea
import io

if 'open' in globals():
    del open
if 'input' in globals():
    del input

original_open = open

class custom_open():
    def __init__(self):
        self.text = ''

    def __call__(self, file, *args, **kwargs):
        if file == 0:
            return io.StringIO(self.text)
        return original_open(file, *args, **kwargs)

    def updater(self, change):
        self.text = change['new']

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)

open = custom_open()
input = custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

In [15]:
N, K = map(int,input().split())
# a_list = []
b_dict = {}

for i in range(N):
    a, b = map(int,input().split())
    if a in b_dict:
        b_dict[a] += b
    else:
        b_dict[a] = b
        
a_list = list(b_dict.keys())
a_list.sort()


for a in a_list:
    K -= b_dict[a]
    if K <= 0:
        break

print(a)

2


In [16]:
b_dict

{1: 999, 2: 1}