In [79]:
a,b,c = input().split()
a = int(a)
b = int(b)
c = int(c)

if a <= c and c <= b:
    print("Yes")
else:
    print("No")

-100 100 50
Yes


In [74]:
-100 <= 50

True

In [75]:
50 <= 100

True

In [76]:
True and True

True

In [77]:
-100 <= 50 <= 100

True

# B Counting Roads

In [20]:
import numpy as np
n,m = input().split()
n = int(n)
m = int(m)
count = np.zeros(n)
for i in range(m):
    a, b = input().split()
    count[int(a)-1] += 1
    count[int(b)-1] += 1

for i in count:
    print(int(i))

8 8
1 2
3 4
1 5
2 8
3 7
5 2
4 1
6 8
3
3
2
2
2
1
1
2


## import numpy as np
c = np.zeros(10)
for i in c:
    print(int(i))

# C bigarray

In [84]:
import numpy as np
n,k = input().split()
n = int(n)
k = int(k)
l = list()
for i in range(n):
    a, b = input().split()
    l.append([int(a),int(b)])

ar = np.array(l)
ar_s = ar.sort(0)
count = np.cumsum(ar_s[:,1])

print(ar_s)
print(count)
print(int(ar_s[np.where(count >=k)[0][0]][0]))

3 4
-1 1
-2 2
-3 3


TypeError: 'NoneType' object is not subscriptable

In [91]:
l = list([[1,2],[2,3],[1,4]])

In [92]:
a = np.array(l)

In [93]:
a

array([[1, 2],
       [2, 3],
       [1, 4]])

In [95]:
a[a[:,0].argsort()]

array([[1, 2],
       [1, 4],
       [2, 3]])

In [87]:
b = np.sort(a,axis=0)

In [89]:
a.sort(0)

In [90]:
a

array([[1, 2],
       [1, 3],
       [2, 4]])

In [88]:
b

array([[1, 2],
       [1, 3],
       [2, 4]])

In [54]:
c = np.cumsum(b[:,1])

In [56]:
np.where(c >=5)[0][0]

1

In [58]:
print(b[np.where(c >=5)[0][0]][0])

1


In [21]:
a = list()
a.append(int(2) * 3)

In [22]:
a

[6]

# D Score Attack

In [69]:
n,m = input().split()
n = int(n)
m = int(m)
l = list()
for i in range(m):
    a,b,c = input().split()
    l.append([int(a),int(b),int(c)])
    
print(l)

2 2
1 2 1
2 1 1
[[1, 2, 1], [2, 1, 1]]


In [ ]:
for i in range(m):
    while 
    

In [71]:
np.array([[1,2],[1,2,3]])

array([[1, 2], [1, 2, 3]], dtype=object)