In [4]:
a,b,c = input().split()
a = int(a)
b = int(b)
c= int(c)

if a == b:
    print(c)
elif b == c:
    print(a)
else:
    print(b)

1 1 7
7


['1123']

In [50]:
h,w = input().split()
h = int(h)
w = int(w)
s_list = []
for _ in range(h):
    s = input()
    s_chars =[]
    for char in s:
        s_chars.append(char)
    s_list.append(s_chars)

import numpy as np
ar = np.array(s_list)
ar = np.insert(ar,0,[["."]*w],axis=0)
ar = np.insert(ar,h+1,[["."]*w],axis=0)
ar = np.insert(ar,0,[["."]*(h+2)],axis=1)
ar = np.insert(ar,w+1,[["."]*(h+2)],axis=1)
answer_list = []
for i in range(1,h+1):
    syoukei = ""
    for j in range(1,w+1):
        if ar[i,j] == ".":
            count = 0
            for k in range(i-1,i+2):
                for l in range(j-1,j+2):
                    if ar[k,l] == "#":
                        count += 1
            syoukei += str(count)
        else:
            syoukei += "#"
    answer_list.append(syoukei)

for ans in answer_list:
    print(ans)

6 6
#####.
#.#.##
####.#
.#..#.
#.##..
#.#...
#####3
#8#7##
####5#
4#65#2
#5##21
#4#310


In [ ]:
6 6
#####.
#.#.##
####.#
.#..#.
#.##..
#.#...

In [40]:
import numpy as np
ar = np.array(s_list)
ar = np.insert(ar,0,[["."]*w],axis=0)
ar = np.insert(ar,h+1,[["."]*w],axis=0)
ar = np.insert(ar,0,[["."]*(h+2)],axis=1)
ar = np.insert(ar,w+1,[["."]*(h+2)],axis=1)
answer_list = []
for i in range(1,h+1):
    syoukei = ""
    for j in range(1,w+1):
        if ar[i,j] == ".":
            count = 0
            for k in range(i-1,i+2):
                for l in range(j-1,j+2):
                    if ar[k,l] == "#":
                        count += 1
            syoukei += str(count)
        else:
            syoukei += "#"
    answer_list.append(syoukei)
    

In [41]:
ar = np.insert(ar,0,[["."]*w],axis=0)
ar = np.insert(ar,h+1,[["."]*w],axis=0)
ar = np.insert(ar,0,[["."]*(h+2)],axis=1)
ar = np.insert(ar,w+1,[["."]*(h+2)],axis=1)
answer_list = []
for i in range(1,h+1):
    syoukei = ""
    for j in range(1,w+1):
        if ar[i,j] == ".":
            count = 0
            for k in range(i-1,i+2):
                for l in range(j-1,j+2):
                    if ar[k,l] == "#":
                        count += 1
            syoukei += str(count)
        else:
            syoukei += "#"
    answer_list.append(syoukei)
    

In [42]:
ar = np.insert(ar,0,[["."]*(h+2)],axis=1)
ar = np.insert(ar,w+1,[["."]*(h+2)],axis=1)
answer_list = []
for i in range(1,h+1):
    syoukei = ""
    for j in range(1,w+1):
        if ar[i,j] == ".":
            count = 0
            for k in range(i-1,i+2):
                for l in range(j-1,j+2):
                    if ar[k,l] == "#":
                        count += 1
            syoukei += str(count)
        else:
            syoukei += "#"
    answer_list.append(syoukei)
    

In [43]:
ar

array([['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '#', '.', '#', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.']], 
      dtype='<U1')

In [44]:
answer_list = []
for i in range(1,h+1):
    syoukei = ""
    for j in range(1,w+1):
        if ar[i,j] == ".":
            count = 0
            for k in range(i-1,i+2):
                for l in range(j-1,j+2):
                    if ar[k,l] == "#":
                        count += 1
            syoukei += str(count)
        else:
            syoukei += "#"
    answer_list.append(syoukei)
    

In [45]:
s_list

[['.', '.', '.', '.', '.'],
 ['.', '#', '.', '#', '.'],
 ['.', '.', '.', '.', '.']]

In [46]:
ar[1,1]

'.'

In [47]:
for i in range(1,h+1):
    syoukei = ""
    for j in range(1,w+1):
        if ar[i,j] == ".":
            count = 0
            for k in range(i-1,i+2):
                for l in range(j-1,j+2):
                    if ar[k,l] == "#":
                        count += 1
            syoukei += str(count)
        else:
            syoukei += "#"
    answer_list.append(syoukei)
    

In [48]:
answer_list

['11211', '1#2#1', '11211']

# C

In [51]:
n,m = input().split()
n = int(n)
m = int(m)
ab_list = []
for i in range(m):
    a,b = input().split()
    a = int(a)
    b = int(b)
    ab_list.append([a,b])


7 7
1 3
2 7
3 4
4 5
4 6
5 6
6 7


In [52]:
ab_list

[[1, 3], [2, 7], [3, 4], [4, 5], [4, 6], [5, 6], [6, 7]]

In [53]:

# D

In [92]:
import numpy as np

n,k = input().split()
n = int(n)
k = int(k)
xy_list = []
for i in range(n):
    x,y = input().split()
    x = int(x)
    y = int(y)
    xy_list.append([x,y])
    
ar = np.array(xy_list)

def menseki_all(ar):
    max_x = ar[:,0].max()
    min_x = ar[:,0].min()
    max_y = ar[:,1].max()
    min_y = ar[:,1].min()
    return (max_x-min_x)*(max_y-min_y)

k_ar = np.ones(len(ar),dtype=bool)
while k_ar.sum() > k:
    max_x_idx = np.argmax(ar[:,0])
    min_x_idx = np.argmin(ar[:,0])
    max_y_idx = np.argmax(ar[:,1])
    min_y_idx = np.argmin(ar[:,1])
    
    max_min_xy_idx = [max_x_idx,min_x_idx,max_y_idx,min_y_idx]
    menseki_list = []
    
    for i in max_min_xy_idx:
        tmp_k_ar = k_ar.copy()
        tmp_k_ar[i] = False
        menseki_list.append(menseki_all(ar[tmp_k_ar]))
    
    ar_menseki = np.array(menseki_list)
    delete_idx = max_min_xy_idx[ar_menseki.argmin()]
    
    ar = np.delete(ar,delete_idx,0)
    k_ar = np.ones(len(ar),dtype=bool)

print(menseki_all(ar))

4 3
-1000000000 -1000000000
1000000000 1000000000
-999999999 999999999
999999999 -999999999
3999999996000000001


In [117]:
import numpy as np

n,m = input().split()
n = int(n)
m = int(m)
xy_list = []
for i in range(n):
    x,y = input().split()
    x = int(x)
    y = int(y)
    xy_list.append([x,y])
    
ar = np.array(xy_list)

def menseki_all(ar):
    max_x = ar[:,0].max()
    min_x = ar[:,0].min()
    max_y = ar[:,1].max()
    min_y = ar[:,1].min()
    return (max_x-min_x)*(max_y-min_y)

menseki = -1
for i in range(n-m):
    tmp_i_ar = ar.copy()
    i_idx = np.argsort(tmp_i_ar[:,0])[:n-i]
    print(tmp_i_ar,i_idx)
    for j in range(n-m-i):
        tmp_j_ar = tmp_i_ar[i_idx].copy()
        j_idx = np.argsort(tmp_j_ar[:,1])[:n-i-j]
        for k in range(n-m-i-j):
            tmp_k_ar = tmp_j_ar[j_idx].copy()
            k_idx = np.argsort(tmp_k_ar[:,0])[k:]
            l = n-m-i-j-k
            tmp_l_ar = tmp_k_ar[k_idx].copy()
            l_idx = np.argsort(tmp_l_ar[:,0])[l:]
            tmp_ar = tmp_l_ar[l_idx]
            tmp_menseki = menseki_all(tmp_ar)
            if menseki == -1:
                menseki = tmp_menseki
            elif menseki > tmp_menseki:
                menseki = tmp_menseki
if menseki == -1:
    menseki = menseki_all(ar)
print(menseki)

4 3
-1000000000 -1000000000
1000000000 1000000000
-999999999 999999999
999999999 -999999999
[[-1000000000 -1000000000]
 [ 1000000000  1000000000]
 [ -999999999   999999999]
 [  999999999  -999999999]] [0 2 3 1]
3999999996000000001


In [115]:
4 3
-1000000000 -1000000000
1000000000 1000000000
-999999999 999999999
999999999 -999999999

[]

In [100]:
np.argsort(ar[:,0])

array([0, 1, 2])

In [98]:
for i in range(0):
    print("a")

In [ ]:
4 3
-1000000000 -1000000000
1000000000 1000000000
-999999999 999999999
999999999 -999999999

In [55]:
xy_list

[[1, 4], [3, 3], [6, 2], [8, 1]]

In [56]:
ar = np.array(xy_list)

def menseki_all(ar):
    max_x = ar[:,0].max()
    min_x = ar[:,0].min()
    max_y = ar[:,1].max()
    min_y = ar[:,1].min()
    return (max_x-min_x)*(max_y-min_y)

k_ar = np.ones(len(ar),dtype=bool)
while k_ar.sum() <= k:
    max_x_idx = np.argmax(ar[:,0])
    min_x_idx = np.argmin(ar[:,0])
    max_y_idx = np.argmax(ar[:,1])
    min_y_idx = np.argmin(ar[:,1])
    
    max_min_xy_idx = [max_x_idx,min_x_idx,max_y_idx,min_y_idx]
    menseki_list = []
    
    for i in max_min_xy_idx:
        tmp_k_ar = k_ar.copy()
        tmp_k_ar[i] = False
        menseki_list.append(menseki_all(ar[tmp_k_ar]))
    
    ar_menseki = np.array(menseki_list)
    delete_idx = max_min_xy_idx[ar_menseki.argmin()]
    
    ar = np.delete(ar,delete_idx,0)
    k_ar = np.ones(len(ar),dtype=bool)

In [68]:
def menseki_all(ar):
    max_x = ar[:,0].max()
    min_x = ar[:,0].min()
    max_y = ar[:,1].max()
    min_y = ar[:,1].min()
    return (max_x-min_x)*(max_y-min_y)

k_ar = np.ones(len(ar),dtype=bool)
while k_ar.sum() <= k:
    max_x_idx = np.argmax(ar[:,0])
    min_x_idx = np.argmin(ar[:,0])
    max_y_idx = np.argmax(ar[:,1])
    min_y_idx = np.argmin(ar[:,1])
    
    max_min_xy_idx = [max_x_idx,min_x_idx,max_y_idx,min_y_idx]
    menseki_list = []
    
    for i in max_min_xy_idx:
        tmp_k_ar = k_ar.copy()
        tmp_k_ar[i] = False
        menseki_list.append(menseki_all(ar[tmp_k_ar]))
    
    ar_menseki = np.array(menseki_list)
    delete_idx = max_min_xy_idx[ar_menseki.argmin()]
    
    ar = np.delete(ar,delete_idx,0)
    k_ar = np.ones(len(ar),dtype=bool)

In [69]:
menseki_all(ar)

21

In [86]:
ar

array([[1, 4]])

In [85]:
k_ar = np.ones(len(ar),dtype=bool)
while k_ar.sum() <= k:
    max_x_idx = np.argmax(ar[:,0])
    min_x_idx = np.argmin(ar[:,0])
    max_y_idx = np.argmax(ar[:,1])
    min_y_idx = np.argmin(ar[:,1])
    
    max_min_xy_idx = [max_x_idx,min_x_idx,max_y_idx,min_y_idx]
    menseki_list = []
    
    for i in max_min_xy_idx:
        tmp_k_ar = k_ar.copy()
        tmp_k_ar[i] = False
        menseki_list.append(menseki_all(ar[tmp_k_ar]))
    
    ar_menseki = np.array(menseki_list)
    delete_idx = max_min_xy_idx[ar_menseki.argmin()]
    
    ar = np.delete(ar,delete_idx,0)
    k_ar = np.ones(len(ar),dtype=bool)

ValueError: zero-size array to reduction operation maximum which has no identity

In [ ]:
menseki_all(ar)

In [71]:
min_x_idx = np.argmin(ar[:,0])

In [76]:
k_ar = np.ones(len(ar),dtype=bool)

In [80]:
k_ar.sum()

3

In [79]:
k_ar[2]=False

In [81]:
k_ar


array([ True,  True, False,  True], dtype=bool)

In [84]:
np.argmax(ar[k_ar][:,0])

2