In [68]:
C = input()
N = list(map(int,input().split()))

count = 0
a = 0
b = 0
for i in range(len(N)-1):
    if N[i+1] - N[i] > 0:
        b = 1
    elif N[i+1] - N[i] < 0:
        b = -1
    else:
        b = 0
        
    if a == 0:
        a = b  
    elif a == b:
        pass
    elif a == b * (-1):
        count += 1
        a = 0
    else:
        pass

print(count+1)
    

7
1 2 3 2 1 99999 1000000000000
3


In [17]:
for i in N:
    print(i)

1
2
1
2
1
2
1
2
1


In [12]:
N[0]

1

# 2

# 3

In [89]:
import numpy as np
from numpy import inf
n,l,t = list(map(int,input().split()))
x_list = list()
w_list = list()

for i in range(n):
    x, w = list(map(int,input().split()))
    x_list.append(x)
    w_list.append(w)

d_list = list()
for i in range(len(x_list)-1):
    d_list.append(x_list[i+1]-x_list[i])
d_list.append(x_list[0]+l-x_list[-1])

w_list = [w if w == 1 else -1 for w in w_list]

x_array = np.array(x_list)
w_array = np.array(w_list)
d_array = np.array(d_list)



time = 0
while time < t:
#     s_list = list()
#     # さが縮まるかどうか。縮まるなら1
#     for i in range(len(w_list)):
#         if w_array[i%n] == 1 and w_array[(i+1)%n]==-1:
#             s_list.append(1)
#         elif w_array[i%n] == -1 and w_array[(i+1)%n]==1:
#             s_list.append(-1)
#         else:
#             s_list.append(0)
    
    s_array = (w_array[1:] - w_array[:-1]) * (-1/2)
    s_array = np.append(s_array,(w_array[0]-w_array[-1])*(-1/2))
#     s_array = np.array(s_list)
    # d_arrayには差が入っている。
    butukaru_array = d_array / (s_array*2)
    butukaru_array[butukaru_array == inf] = 0
    butukaru_array[butukaru_array == -inf] = 0
    if s_array.all == 0:
        next_time = t -time
    else:
        next_time = butukaru_array.max()

    time += next_time
        
    if time >= t:
        next_time -= (time-t)
    
    x_array = (x_array + w_array*next_time) % l
    if time >= t:
        break
    d_array = d_array - s_array*2*next_time

    butukatta_x = np.where(d_array == 0)[0]
    
#     for i in butukatta_x:
    w_array[butukatta_x] *= -1
    w_array[(butukatta_x+1)%n] *= -1
    
for x in x_array:

    while x<0:
        x += l
    while x >= l:
        x -= l
        
    print(int(x))

4 20 9
7 2
9 1
12 1
18 1
7
18
18
1


/Users/takizawa/dev/python/atcoder/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: divide by zero encountered in true_divide


In [88]:
d_array

array([ 2.,  5.,  1.])

In [34]:
[x if x % 3 == 0 else 'fizz' for x in range(10)]

[0, 'fizz', 'fizz', 3, 'fizz', 'fizz', 6, 'fizz', 'fizz', 9]

In [63]:
a = np.array([1,2,3])

b = np.array([9,8,7,6,5,4])

# for i in a:
#     b[i] *= -1
    
b[a+1]*= -1
b

array([ 9,  8, -7, -6, -5,  4])

In [44]:
3 8 3
0 1
3 2
6 1

SyntaxError: invalid syntax (<ipython-input-44-a23c8defd53f>, line 1)

In [45]:
a = np.array([1,2,3])
for i in a:
    print(i)

1
2
3


In [47]:
s_array

array([-1,  1,  0])

In [71]:
a = np.array([0,0,0])
(a ==0).any()

True

In [76]:
butukatta_x+1

TypeError: can only concatenate tuple (not "int") to tuple

In [78]:
np.where(d_array == 0)[0]

array([0])

In [85]:
a = np.array([1,2,3])
b = 2
a % b

array([1, 0, 1])