# A

In [9]:
a,b,c = input().split()
a = int(a)
b = int(b)
c = int(c)

print(int(a * b / 2))

45 28 53
630


In [7]:
a


3

# B

In [15]:
s = int(input())

a = s

a_list = [a]

while True:
    if a %2 == 0:
        a = a/2
    else:
        a = 3*a + 1
        
    if a in a_list:
        break
    
    a_list += [a]

print(len(a_list) + 1)

1
4


# C


In [23]:
n = int(input())
h_list = list(map(int,input().split()))

mizu = 0

for i in range(len(h_list)-1):
    if h_list[i] > h_list[i+1]:
        mizu += h_list[i] - h_list[i+1]
        
mizu += h_list[-1]

print(mizu)

8
4 23 75 0 23 96 50 100
221


# D

In [28]:
import numpy as np

n,k = map(int, input().split())

l =[]
for i in range(n):
    l += [list(map(int,input().split()))]

7 4
1 1
2 1
3 1
4 6
4 5
4 5
4 5


In [110]:
ar = np.array(l)
ar = ar[np.argsort(ar[:,1])][::-1]
ar = np.concatenate([ar, np.zeros([ar.shape[0],1])],1)

l = ar[np.argsort(ar[:,1])][::-1].tolist()

In [111]:
l

[[4.0, 6.0, 0.0, 0.0],
 [4.0, 5.0, 0.0, 0.0],
 [4.0, 5.0, 0.0, 0.0],
 [4.0, 5.0, 0.0, 0.0],
 [3.0, 1.0, 0.0, 0.0],
 [2.0, 1.0, 0.0, 0.0],
 [1.0, 1.0, 0.0, 0.0]]

In [106]:
t_list = []
for r in l:
    

[[4, 6], [4, 5], [4, 5], [4, 5], [3, 1], [2, 1], [1, 1]]

In [57]:
np.concatenate([ar, np.zeros([ar.shape[0],1])],1)

array([[1., 1., 0.],
       [2., 1., 0.],
       [3., 1., 0.],
       [4., 6., 0.],
       [4., 5., 0.],
       [4., 5., 0.],
       [4., 5., 0.]])

In [31]:
ar = np.array(l)

ar[np.argsort(ar[:,1])[::-1]]

In [37]:
ar

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 6],
       [4, 5],
       [4, 5],
       [4, 5]])

In [58]:
ar_rank = np.concatenate([ar, np.zeros([ar.shape[0],1])],1)

In [85]:
n

7

In [86]:
b

array([[4., 6., 0.],
       [4., 5., 0.],
       [4., 5., 0.],
       [4., 5., 0.],
       [3., 1., 0.],
       [2., 1., 0.],
       [1., 1., 0.]])

In [94]:
b = ar_rank[np.argsort(ar_rank[:,1])[::-1]]
for i in list(np.unique(ar_rank[:,0])):
    b[b[:,0]==int(i)][0,2] = 1

In [99]:
b[b[:,0]==int(1)]

array([[1., 1., 0.]])

In [80]:
b = ar_rank[np.argsort(ar_rank[:,1])[::-1]]

In [79]:
b[b[:,0]==4][0,2]

0.0

In [61]:
np.argsort(ar_rank[ar_rank[0]==1][:,1])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3

In [48]:
riyou_ar = ar[np.argsort(ar[:,1])[::-1]][:3]

In [49]:
oisisa_yuusen = riyou_ar[:,1].sum()

In [53]:
kizon_t = np.unique(riyou_ar[:,0])

https://atcoder.jp/contests/abc116/submissions/4056403

In [112]:
from heapq import heappush, heappop
 
N, K = map(int, input().split())
h = []
for i in range(N):
    t, d = map(int, input().split())
    heappush(h, (-d, t))
    
# initial
res = 0
sum = 0
q = []
used = {}
for i in range(K):
    (d, t) = heappop(h)
    if t not in used:
        used[t] = 1
    else:
        heappush(q, (-d, t))
    sum += -d
res = len(used)*len(used)+sum
 
# swap minimum
while q and h:
    (d, t) = heappop(h)
    if t not in used:
        used[t] = 1
        m, _ = heappop(q)
        sum = sum - m - d
    res = max(res, len(used)*len(used) + sum)
    
print(res)

5 3
1 9
1 7
2 6
2 5
3 1
26
